### PR TITLE
Fix migrations and several other bugs for 1.0.x

### PR DESCRIPTION
**Pull request by JDutil**

### CODE REVIEW

**Comment by westonplatter** [comment]
@jdutil - **awesome work** with updating for the Spree namespacing. 

A word of caution, modifying committed migrations is not the best idea. The safer route is to create new migraitons that change the table names. That way, someone migrating up from scatch does not get derailed.

**Comment by JDutil** [comment]
I forget my exact rationale since it was awhile ago when I did this, but I believe I had to change the migrations because they didn't run trying to install into a fresh app from scratch.

**Comment by theCrab** [comment]
yes the migrations are not really working

**Comment by JDutil** [comment]
@theCrab I have absolutely no interest in working on this anymore as I was only experimenting with whether the extension would meet my needs or not.  It didn't and there is no interest in merging this so I've started http://github.com/jdutil/spree_drop_ship if your interested in trying that out.

**Comment by theCrab** [comment]
yeah I noticed. There no even validations

**Pull request closed without merging**
